name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - development

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Show Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      # Custom domain is at the root (/),
      # so Flutter must NOT use /ghost_song_player/
      - name: Build Flutter Web
        run: flutter build web --release --base-href "/"

      # Keep the custom domain after every deployment
      - name: Add custom domain
        run: echo "renuka.jayaramdhungana.com.np" > build/web/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4